version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-db
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis-insight
    restart: always
    depends_on:
      - redis
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db

  qdrant:
    image: qdrant/qdrant:v1.4.0
    container_name: qdrant-db
    restart: always
    ports:
      - 6333:6333
    volumes:
      - qdrant_volume_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: my-flask-app
    depends_on:
      - redis
      - qdrant
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - QDRANT_HOST=qdrant
    restart: always

volumes:
  redis_volume_data:
  redis_insight_volume_data:
  qdrant_volume_data:
