services:
  flask_app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    networks:
      - mynet
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    # depends_on:
    #   - app
    networks:
      - mynet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  mynet:
    driver: bridge