# Use official Python base image
FROM python:3.10-slim

ENV TZ="Asia/Bangkok"

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements and install them
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

RUN chmod +x ./entrypoint.sh

# Expose the port used by Gunicorn
EXPOSE 5000

# Start the app using Gunicorn
ENTRYPOINT ["./entrypoint.sh"]
# CMD ["gunicorn", "-c", "gunicorn.conf.py", "app:app"]