version: "3.3"
services:
  redis:
    image: redis:latest
    container_name: redis-db
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis-insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
  qdrant:
    image: qdrant/qdrant:v1.4.0
    container_name: qdrant-db
    restart: always
    ports:
      - 6333:6333
    volumes:
      - qdrant_volume_data:/qdrant/storage
volumes:
  redis_volume_data:
  redis_insight_volume_data:
  qdrant_volume_data: