# Use official Python base image
FROM python:3.11-slim

# Set timezone environment variable
ENV TZ="Asia/Bangkok"

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .

# RUN pip install --no-cache -dir -r requirements.txt

RUN pip install -r requirements.txt

# Copy the rest of the application
COPY . .

# Ensure entrypoint.sh has Unix line endings and is executable
RUN chmod +x ./entrypoint.sh

# Expose the port used by Gunicorn
EXPOSE 5000

# Start the app using Gunicorn
ENTRYPOINT ["./entrypoint.sh"]
